### ISSUE TITLE
Making Science simple and accessible

### ISSUE THREAD

**Issue by Romullol** [open-life-science/ols-6#12]
Project Lead: @romullol, Fabio

Mentor: Andrea, Gracielle

Welcome to OLS-6! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Life Science program :tada:.

***

## Week 1: Meet your mentor!
- [x] Meet mentor for 30 minutes 
- [x] Create an account on [GitHub](https://github.com)
- [ ] Check if you have access to the HackMD notes set up for your meetings with your mentor
- [ ] Prepare to meet your mentor(s) by completing a short homework provided in your shared notes
- [ ] Complete **your own copy** of the [open leadership self-assessment](https://docs.google.com/document/d/1oQgdfj4lPnypAyb9_Ba0Zt7E8J5L6qMvuKwu0wgQsjs/edit?usp=sharing) and share it to your mentor 
  If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

## Week 2 - Cohort Call (Welcome to Open Life Science!)

- [x] Attend call or catch up via YouTube
- [ ] Create an issue on the [OLS-6 GitHub repository](https://github.com/open-life-science/OLS-6/issues/new) for your OLS work and share the link to your mentor.
- [ ] Draft a brief vision statement using your goals

  [This lesson](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/) from the Open Leadership Training Series (OLTS) might be helpful

- [ ] Leave a comment on this issue with your draft vision statement & be ready to share this on the call
- [ ] Check the [Syllabus](https://openlifesci.org/ols-6) for notes and connection info for all the cohort calls.

## Week 3: Meet your mentor!

- [ ] Meet mentor
- [ ] Look up two other projects and comment on their issues with feedback on their vision statement
- [ ] Complete this [compare and contrast assignment](https://docs.google.com/document/d/1ukvqDRIYfvCapVMdE5hWP-0MkLNJ9T65X43O7F336Ac/edit?usp=sharing) about current and desired community interactions and value exchanges
- [ ] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://docs.google.com/presentation/d/1MeJo0TyuMg_waLk1J4q9y1aAqKNMuRBlnmxEChSz-cQ/edit?usp=sharing))
- [ ] Share a link to your Open Canvas in your GitHub issue
- [ ] Start your [Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/)
- [ ] Comment on your issue with your draft Roadmap
- [ ] Suggest a cohort name at the bottom of the shared notes and vote on your favorite with a +1

## Week 4: Cohort Call (Tooling and roadmapping for Open projects)

- [ ] Attend call or catch up via YouTube
- [ ] Look up two other projects and comment on their issues with feedback on their open canvas.

## Week 5 and later
- [ ] Meet mentor
- [ ] Create a GitHub repository for your project
- [ ] Add the link to your repository in your issue
- [ ] Use your canvas to [start writing a `README.md` file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project
- [ ] Link to your README in a comment on this issue
- [ ] Add an [open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) to your repository as a file called `LICENSE.md`
- [ ] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/) to your repository as a file called `CODE_OF_CONDUCT.md`
- [ ] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Life Science program. Please refer to the [OLS-6 Syllabus](https://openlifesci.org/OLS-6) for more detailed weekly notes and assignments past week 4.

## Week 6 
- [ ] Attend call or catch up via YouTube

## Week 7
- [ ] Meet mentor

## Week 8
- [ ] Attend call or catch up via YouTube

## Week 9
- [ ] Meet mentor

## Week 10
- [ ] Attend call or catch up via YouTube

## Week 11
- [ ] Meet mentor

## Week 12
- [ ] Attend call or catch up via YouTube

## Week 13
- [ ] Meet mentor

## Week 14
- [ ] Attend call or catch up via YouTube

## Week 15
- [ ] Meet mentor

**Comment by Susana465** [comment]
The title of this project seems really interesting and broad - I look forward to learning more about it!

**Comment by Romullol** [comment]
Here is the [Open Canvas](https://docs.google.com/presentation/d/1y5cwrUtEZT6Tl7D5Mf-kDfLbRxTJ3NiT/edit?usp=sharing&ouid=100957140696319530761&rtpof=true&sd=true). Any comments are welcome =)

**Comment by Romullol** [comment]
This is our draft **vision statment**. 
"We are building a community of scientists, teachers and enthusiasts of biology. We aim to build a collection of open material. Teachers can use them to teach, in a simpler way, the scientific ecological knowledge to high school students. With the basis of scientific thinking and methods, students will  become more critical. And thus agents of their own transformation."

**Comment by Romullol** [comment]
**ROADMAP**

**Project Name**: Making Ecology Simple and Accessible
**Summary:** Building a platform that organize and publishes open ecological resources to be used by brazilian teachers and educators in Ecology classes and events

**This project for now, is divided in two phases:** 
The first one is to create a more simple platform, that only gathers links to content that already exists online.
The second part is to “upgrade” our site so creators could publish their resources in our platform

**This roadmap refers to the first phase of our project**

**1st milestone:** Build a map of the site

- Investigate brazilian biology curriculum for each grade and annotate all ecology content _(this will be needed to organize the site in categories)_
- Improve the name of the project _(it is too long and not so catchy)_
- Ask for people to help in our project _(web digging, site editing, digital art)_
- Look at github to learn how the site could be _(to know the functionalities of github when making a platform and how to make it on github)_
- Build the first draft of the map _(to have something to show to teachers so they can criticize it)_
- Talk to at least 20 teachers and creators to listen some suggestions about the list of content and organization of the site _(since our site will be made for them, is nice to hear from them how this need to be)_
- Finish the map of the site _(how we want our site to be organized)_


2nd milestone: Build the site

- Discuss how each page needs to be _(each link will be in a different page with tons of description or there will be a page with all links listed? Or maybe both?)_
- Organize the pages of the platform basing on our map _(our site will begin to gain form)_
- Ask for people to help in our project _(web digging, site editing, digital art)_
- Dig the web for content for each ecology subject  
- Put the links in the right pages of our site _(to fill our pages with knowledge!)_ 
- Share it to everyone!

**How can you contribute?**
Since we are in phase 1, we need three types of contributors
**Obs: We don't have any form yet, so if you want to contribute you can do so by answering this issue or reaching us on slack**

**Anyone:**
Do you know any ecological resources in pt-br available online? Send us the link so we can put it on our site. [Link form].
Do you have any suggestions about how this platform could be or what it must have to be a good platform? Send it to us via this [suggestion form]

**Brazilian teachers and educators**
We need your expertise to know what the ecology content that is taught at brazilian school and how it is organized.
We want to hear from you how you like our platform to be. What do you miss the most when searching for resources online?
You can contribute via this [suggestion form] or via meetings or text talks

**Creators**
Do you have any resources online? Send us the link so our platform could redirect it to your site. 
We want to hear from you how you like our platform to be. Which features it must have to be a good platform to share your work?
Do you have time and want to learn and to participate more actively in our project? Tell us a little about yourself [form] and we could find some functions for you

---------------------


**For the future, after phase 2 (Dream big)**
Make this platform international, assigning the language of each material and allowing that each resource could be translated
To publish an online journal based on the resources of the site. Where each article talks about the resource uploaded (how to use, use context,  experience reports)

**Comment by mlagisz** [comment]
Hi, I love your project and you made great progress so far! Do you plan to have any plans to include materials on open science and robust research methodology in relation to ecological knowledge? I think this would align nicely (although is usually not a part of school curriculum).

**Comment by pharouknucleus** [comment]
This is great. Making science open is all about sharing knowledge and skills. However, what is the overall outcome you are aiming to achieve?

**Comment by babasaraki** [comment]
This is really a nice project. However, I couldn't figure out your mission and vision statement clearly. These might be something to look into? All the best with your project.

**Comment by macziatko** [comment]
Seeing all versions of your Open Canva give a great overview of how the vision of your project developed. Great job!
